# Imports

In [14]:
import numpy as np
import os

# View org seed

In [38]:
# Load file
org_seed = np.load('seed.npz')

# Show keys
keys = org_seed.files
print(f"Keys in the NPZ file: \n{keys}\n\n")


for key in keys:
    print(key)
    print(org_seed[key].shape)
    print(org_seed[key])
    print()


# Close file
org_seed.close()

Keys in the NPZ file: 
['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']


fc1.weight
(64, 784)
[[-0.00982534  0.01858591 -0.01912403 ... -0.01184074 -0.00723694
   0.01230336]
 [ 0.02853655  0.00238311 -0.0189479  ... -0.02400594  0.00158385
  -0.00842472]
 [ 0.02082591  0.02017024  0.03557282 ... -0.02475919 -0.02295317
  -0.00196025]
 ...
 [ 0.00458845 -0.00022928  0.00977486 ... -0.00528903  0.03072966
  -0.02158209]
 [ 0.03216585  0.01068309 -0.00528849 ...  0.00193949  0.00418663
  -0.01608332]
 [-0.02645003 -0.03071633 -0.00172928 ...  0.0009959  -0.00640547
   0.01506463]]

fc1.bias
(64,)
[-0.0063847   0.00574812 -0.02030971  0.00205287  0.0272533  -0.00378571
  0.00364715 -0.03241104 -0.03212726 -0.0224267  -0.01744068 -0.00604857
  0.00653063  0.01201137  0.01626732 -0.00761071  0.01374387  0.00364367
 -0.01635192  0.02345245 -0.00718861  0.01193707  0.02287747 -0.00731025
  0.00355967 -0.00860439  0.0035525  -0.02606844 -0.03490189 -0.01527876
 -

# Create new seed

In [39]:
def create_new_seed_file():
    try:
        # Set keys
        keys = ['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']
        
        # Set layers sizes
        shapes = [(64, 784), (64,), (32, 64), (32,), (10, 32), (10,)]
        
        # Set new seed path:
        new_seed_path = "random_seed.npz"

        # Dictionary to hold new data
        new_data = {}

        # Iterate over keys in the original file
        for i in range(len(keys)):
            # Get the key
            key = keys[i]
            
            # Get the shape
            shape = shapes[i]

            # Generate new random data with the same shape
            new_data[key] = np.random.rand(*shape)/10

        # Save new data to a new seed file
        np.savez(new_seed_path, **new_data)

        print("Random seed created!")

    except Exception as e:
        print(f"An error occurred: {e}")


create_new_seed_file()

Random seed created!


# View new random seed

In [40]:
# Load file
random_seed = np.load('random_seed.npz')

# Show keys
keys = random_seed.files
print(f"Keys in the NPZ file: \n{keys}\n\n")

for key in keys:
    print(key)
    print(random_seed[key].shape)
    print(random_seed[key])
    print()


# Close file
random_seed.close()

Keys in the NPZ file: 
['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']


fc1.weight
(64, 784)
[[0.02848134 0.08697873 0.06773282 ... 0.01022323 0.04186107 0.01610164]
 [0.03536932 0.00374863 0.01193142 ... 0.01363803 0.02139323 0.0185389 ]
 [0.07853671 0.07249686 0.01067796 ... 0.06584553 0.03120596 0.026847  ]
 ...
 [0.09974236 0.0096973  0.07014873 ... 0.01692092 0.05927529 0.00919617]
 [0.02985079 0.06058526 0.0545864  ... 0.0426983  0.08425947 0.08209068]
 [0.04037234 0.08786368 0.04878909 ... 0.01604194 0.02440711 0.00650866]]

fc1.bias
(64,)
[0.07455882 0.06380291 0.01368177 0.06550431 0.08178802 0.09742629
 0.09804699 0.04100625 0.0627625  0.0405141  0.05126748 0.03993905
 0.00523764 0.03013945 0.09143694 0.07841617 0.06435247 0.05724879
 0.00601271 0.08741225 0.03630571 0.09454043 0.08390926 0.01336722
 0.05509431 0.05638096 0.05872258 0.03021402 0.03856669 0.05391965
 0.03738693 0.06812612 0.03735567 0.05727114 0.03268369 0.06323553
 0.02341308 0