# Import

In [14]:
import torch
import os

# Troubleshoot

In [25]:
# Base path
file_path = '/Users/Edvin/Desktop/Project/fedn/examples/mnist-pytorch/data/clients'

num_clients = sum(os.path.isdir(os.path.join(file_path, i)) for i in os.listdir(file_path))

# Loop through each file
for i in range(1, num_clients):
    # Construct the file path
    file = f"{file_path}/{i}/mnist.pt"

    # Load the file
    data = torch.load(file)

    # Check the type and contents of the loaded data
    print(f"\nClient {i}:")
    print(data["y_train"])
    print(len(data["y_train"]))


Client 1:
tensor([5, 0, 4,  ..., 2, 8, 3])
12000

Client 2:
tensor([7, 4, 6,  ..., 3, 9, 4])
12000

Client 3:
tensor([8, 5, 8,  ..., 8, 7, 0])
12000

Client 4:
tensor([9, 2, 6,  ..., 0, 1, 2])
12000
