# Imports

In [14]:
import numpy as np
import os

# View org seed

In [18]:
# Load file
org_seed = np.load('seed.npz')

# Show keys
keys = org_seed.files
print(f"Keys in the NPZ file: \n{keys}\n\n")


for key in keys:
    print(key)
    print(org_seed[key].shape)
    print(org_seed[key])
    print()


# Close file
org_seed.close()

Keys in the NPZ file: 
['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']


fc1.weight
(64, 784)
[[-0.00982534  0.01858591 -0.01912403 ... -0.01184074 -0.00723694
   0.01230336]
 [ 0.02853655  0.00238311 -0.0189479  ... -0.02400594  0.00158385
  -0.00842472]
 [ 0.02082591  0.02017024  0.03557282 ... -0.02475919 -0.02295317
  -0.00196025]
 ...
 [ 0.00458845 -0.00022928  0.00977486 ... -0.00528903  0.03072966
  -0.02158209]
 [ 0.03216585  0.01068309 -0.00528849 ...  0.00193949  0.00418663
  -0.01608332]
 [-0.02645003 -0.03071633 -0.00172928 ...  0.0009959  -0.00640547
   0.01506463]]

fc1.bias
(64,)
[-0.0063847   0.00574812 -0.02030971  0.00205287  0.0272533  -0.00378571
  0.00364715 -0.03241104 -0.03212726 -0.0224267  -0.01744068 -0.00604857
  0.00653063  0.01201137  0.01626732 -0.00761071  0.01374387  0.00364367
 -0.01635192  0.02345245 -0.00718861  0.01193707  0.02287747 -0.00731025
  0.00355967 -0.00860439  0.0035525  -0.02606844 -0.03490189 -0.01527876
 -

# Create new seed

In [22]:
def create_new_seed_file():
    # Set keys
    keys = ['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']
    
    # Set layers sizes
    shapes = [(64, 784), (64,), (32, 64), (32,), (10, 32), (10,)]
    
    # Set new seed path:
    new_seed_path = "random_seed_2.npz"

    # Dictionary to hold new data
    new_data = {}

    # Iterate over keys in the original file
    for i in range(len(keys)):
        # Get the key
        key = keys[i]
        
        # Get the shape
        shape = shapes[i]

        # Generate new random data with the same shape
        new_data[key] = np.random.rand(*shape)

    # Save new data to a new seed file
    np.savez(new_seed_path, **new_data)

    # Close the original seed file
    org_seed.close()


create_new_seed_file()

# View new random seed

In [24]:
# Load file
random_seed = np.load('random_seed_2.npz')

# Show keys
keys = random_seed.files
print(f"Keys in the NPZ file: \n{keys}\n\n")

for key in keys:
    print(key)
    print(random_seed[key].shape)
    print(random_seed[key])
    print()


# Close file
random_seed.close()

Keys in the NPZ file: 
['fc1.weight', 'fc1.bias', 'fc2.weight', 'fc2.bias', 'fc3.weight', 'fc3.bias']


fc1.weight
(64, 784)
[[0.61303268 0.33351886 0.92526206 ... 0.01747832 0.4966243  0.13830828]
 [0.22339029 0.97074427 0.70982695 ... 0.72117391 0.19603638 0.68005961]
 [0.81661182 0.28214871 0.12405918 ... 0.81408047 0.65799974 0.14011636]
 ...
 [0.87929718 0.81723247 0.19618565 ... 0.8575428  0.35554691 0.58939019]
 [0.28723954 0.09429786 0.12171454 ... 0.36777174 0.76009165 0.08916751]
 [0.75082297 0.67262735 0.21293247 ... 0.23942071 0.05506001 0.51587031]]

fc1.bias
(64,)
[0.4782711  0.69131022 0.49323027 0.21350375 0.58495752 0.71407247
 0.85243454 0.56607563 0.46229485 0.52444677 0.92083753 0.16938248
 0.33051082 0.30309076 0.34289544 0.51366259 0.49558309 0.97131642
 0.29641859 0.71666475 0.30089471 0.20230454 0.3758083  0.98027554
 0.09058898 0.85586445 0.35189868 0.06338809 0.70215413 0.19124718
 0.83430035 0.45618779 0.29517392 0.5158709  0.54111005 0.32024206
 0.71990273 0